name:                type-inference-zoo
version:             0.1.0.0
github:              "cu1ch3n/type-inference-zoo"
license:             MIT
author:              "Chen Cui"
maintainer:          "i@cuichen.cc"
copyright:           "2025 Chen Cui"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/cu1ch3n/type-inference-zoo#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- containers
- hspec
- logict
- megaparsec
- mtl
- parser-combinators
- transformers
- tree-view
- unbound-generics

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  type-inference-zoo-exe:
    main:                Main.hs
    source-dirs:         app
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - type-inference-zoo

tests:
  type-inference-zoo-test:
    main:                Spec.hs
    source-dirs:         test
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - type-inference-zoo
